name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Get version number
      id: version
      run: |
        # 读取当前版本号，如果文件不存在则从1开始
        if [ -f "version.txt" ]; then
          CURRENT_VERSION=$(cat version.txt)
        else
          CURRENT_VERSION=0
        fi
        NEW_VERSION=$((CURRENT_VERSION + 1))
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT
        echo $NEW_VERSION > version.txt
        echo "当前版本号: $NEW_VERSION"

    - name: Grant Gradle permissions
      run: chmod +x ./gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Generate release info
      id: release_info
      run: |
        DATE=$(date +"%Y%m%d")
        VERSION="${{ steps.version.outputs.version }}"
        
        # 生成 hash（使用当前时间戳）
        HASH=$(echo "${{ github.run_id }}" | sha256sum | cut -c1-8)
        
        APK_NAME="apk-${DATE}-${HASH}-v${VERSION}.apk"
        RELEASE_TAG="v${DATE}-${HASH}-${VERSION}"
        RELEASE_TITLE="apk-${DATE}-${HASH}-${VERSION}"
        
        echo "apk_name=$APK_NAME" >> $GITHUB_OUTPUT
        echo "release_tag=$RELEASE_TAG" >> $GITHUB_OUTPUT
        echo "release_title=$RELEASE_TITLE" >> $GITHUB_OUTPUT
        
        echo "APK名称: $APK_NAME"
        echo "Release标签: $RELEASE_TAG"
        echo "Release标题: $RELEASE_TITLE"

    - name: Rename APK
      run: |
        mkdir -p release_apk
        cp app/build/outputs/apk/debug/app-debug.apk "release_apk/${{ steps.release_info.outputs.apk_name }}"
        echo "APK已重命名为: ${{ steps.release_info.outputs.apk_name }}"

    - name: Commit version update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add version.txt
        git commit -m "Update version to ${{ steps.version.outputs.version }}" || exit 0

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.release_info.outputs.apk_name }}
        path: release_apk/${{ steps.release_info.outputs.apk_name }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        name: "${{ steps.release_info.outputs.release_title }}"
        tag_name: "${{ steps.release_info.outputs.release_tag }}"
        body: |
          **APK 构建发布**
          **构建信息**: ${{ steps.release_info.outputs.release_title }}
          **文件**: ${{ steps.release_info.outputs.apk_name }}
          **版本号**: v${{ steps.version.outputs.version }}
          
        files: release_apk/${{ steps.release_info.outputs.apk_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}